### ISSUE TITLE
没有二次元的鸿蒙吗？想到一个肥猪在意淫这一堆我就想吐

### ISSUE THREAD

**Issue by hktiy** [histion/lora-kujo_miyako#1]

**Comment by histion** [comment]
哈哈，真可怜，米猴这么应激啊？

**Comment by histion** [comment]
没母的消愁不去你猴头主子那里报团取暖跑来这里找你野爹拷打？米猴斯德哥尔摩综合症发作了？😁

**Comment by histion** [comment]
你这小太监还挺幽默的，你主子给你喂得狗粮挺饱啊跑外面到处咬人🤣

**Comment by histion** [comment]
没有现实中的父母吗？想到一个36岁无业肥猪在把github的issue当国内恶臭讨论当猴子猴孙我就想吐☺

**Comment by histion** [comment]
这边真切的祝愿你永生永世亲朋好友开su7

**Comment by histion** [comment]
&#129313;马戏团里你最忙，哥谭市里你最狂。&#129313;

&#129313;麦当劳前你站岗，扑克牌里大小王。&#129313;

**Comment by histion** [comment]
有澎湃OS吗？有AI狂暴引擎吗？有2K屏吗？有冰封循环冷泵吗？有超窄视觉四等边直屏吗？有全等深微曲屏吗？有71.5mm黄金尺寸设计吗？有高能密度碳硅电池吗？有澎湃电池管理系统吗？有莱卡光学莱卡summilux镜头莱卡浮动长焦莱卡超广角吗？有无极可变光圈吗？有小米影像大脑吗？有龙晶玻璃吗？有第三代ESA技术的定制马达吗。有王一博吗？销量不到k70的零头，别扯了。
