### ISSUE TITLE
我真的笑死，你以为自己改了别的人标题后，其他人能看到吗？

### ISSUE THREAD

**Issue by diwiki2628** [histion/lora-kujo_miyako#2]
![image](https://github.com/histion/lora-kujo_miyako/assets/171202371/d35561b6-c468-43cc-a1bc-ab0fa1037959)
你是不是长这样？
![image](https://github.com/histion/lora-kujo_miyako/assets/171202371/e6961932-623e-4275-af53-813f66d9c7eb)

**Comment by histion** [comment]
这不是你爹吗哈哈，继续开小号，小畜生，玩国内论坛入脑的低能可真可怜，天天把脸靠过来给人扇😁

**Comment by histion** [comment]
你的人生是多失败，天天来网上找存在感🤣是现实中没朋友吗，真可怜小丑，刺激的你封号了隔了几个月也要上来继续送脸给你野爹我扇打

**Comment by histion** [comment]
别人能不能看我不知道，我只知道能刺激到你这神蛆就行了🤗
